file=open('24-01.txt', 'r')
s=file.readline().strip()
s=s.replace("AB", "A B")
s=s.replace("BA", "B A")
s=s.replace("CA", "C A")
s=s.replace("AC", "A C")
s=s.replace("CB", "C B")
s=s.replace("BC", "B C")
all_lines=s.split()
x=s.split()
print(len(max(x,key=len)))        
# ответ 35
